DjangoProjekat/DjangoProjekat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('treninzi.urls'))
]

DjangoProjekat/treninzi/urls.py
from django.urls import path
from . import views

app_name = 'demo_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('practices/', views.practices, name='practices'),
    path('practice/<int:id>', views.practice, name='practice'),
    path('practice/edit/<int:id>', views.edit, name='edit'),
    path('practice/new/', views.new, name='new')
]

DjangoProjekat/treninzi/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class Practice(models.Model):
    type = models.CharField(max_length=16)
    location = models.CharField(max_length=32)
    content = models.TextField(max_length=200)
    rate = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    hours = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)])
    minutes = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(60)])
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    practice = models.ForeignKey(Practice, on_delete=models.CASCADE)

DjangoProjekat/treninzi/forms.py
from django.forms import ModelForm
from .models import Practice, Comment

class PracticeForm(ModelForm):
    class Meta:
        model = Practice
        fields = ['type', 'location', 'content', 'rate', 'hours', 'minutes']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

DjangoProjekat/treninzi/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Practice
from .forms import PracticeForm
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
# Create your views here.


def index(req):
    if not req.user.is_authenticated:
        return render(req, 'index.html', {'page_title': 'Naslov Stranice'})
    else:
        return redirect('demo_app:practices')


@login_required
def practices(req):
    tmp = Practice.objects.all()
    return render(req, 'practices.html', {'practices': tmp})


@login_required
def practice(req, id):
    tmp = get_object_or_404(Practice, id=id)
    return render(req, 'practice.html', {'practice': tmp, 'page_title': tmp.type})


@permission_required('demo_app.change_practice')
def edit(req, id):
    if req.method == 'POST':
        form = PracticeForm(req.POST)

        if form.is_valid():
            p = Practice.objects.get(id=id)
            p.type = form.cleaned_data['type']
            p.location = form.cleaned_data['location']
            p.content = form.cleaned_data['content']
            p.rate = form.cleaned_data['rate']
            p.hours = form.cleaned_data['hours']
            p.minutes = form.cleaned_data['minutes']
            p.save()
            return redirect('demo_app:practices')
        else:
            return render(req, 'edit.html', {'form':form, 'id':id})
    else:
        p = Practice.objects.get(id=id)
        form = PracticeForm(instance=p)
        return render(req,'edit.html',{'form':form, 'id':id})


@permission_required('treninzi.add_practice')
def new(req):
    if req.method == 'POST':
        forma = PracticeForm(req.POST)
        if forma.is_valid():
            p = Practice(type = forma.cleaned_data['type'], location = forma.cleaned_data['location'], content = forma.cleaned_data['content'], rate = forma.cleaned_data['rate'], hours = forma.cleaned_data['hours'], minutes = forma.cleaned_data['minutes'], owner= req.user)
            p.save()
            return redirect('demo_app:practices')
        else:
            return render(req, 'new.html', {'form': forma})
    else:
        forma = PracticeForm()
        return render(req, 'new.html', {'form': forma})

DjangoProjekat/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'demo_app:practices' %}">
        Practice review
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            {% if not perms.demo_app.add_article %}
                <a class="nav-link disabled" href="{% url 'demo_app:new' %}">New practice</a>
            {% else %}
                <a class="nav-link" href="{% url 'demo_app:new' %}">New practice</a>
            {% endif %}
        </li>
    </ul>

    {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout {{ user.get_username }}</a>
    {% endif %}

</nav>

DjangoProjekat/templates/master.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        {% include 'header.html' %}

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>

DjangoProjekat/treninzi/templates/edit.html
{% extends 'master.html' %}

{% block title %}
    Edit article
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:edit' id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.type.id_for_label }}">{{ form.type.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.type.id_for_label }}" name="{{ form.type.name }}" value="{{ form.type.value }}">
            {% if form.type.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.type.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.location.id_for_label }}">{{ form.location.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.location.id_for_label }}" name="{{ form.location.name }}" value="{{ form.location.value }}">
            {% if form.location.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.location.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.rate.id_for_label }}">{{ form.rate.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.rate.id_for_label }}" name="{{ form.rate.name }}" value="{{ form.rate.value }}">
            {% if form.rate.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.rate.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.hours.id_for_label }}">{{ form.hours.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.hours.id_for_label }}" name="{{ form.hours.name }}" value="{{ form.hours.value }}">
            {% if form.hours.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.hours.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.minutes.id_for_label }}">{{ form.minutes.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.minutes.id_for_label }}" name="{{ form.minutes.name }}" value="{{ form.minutes.value }}">
            {% if form.minutes.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.minutes.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5">{{ form.content.value }}</textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Save"/>
    </form>

{% endblock %}

DjangoProjekat/treninzi/templates/index.html
{%  extends 'master.html' %}

{%  block content %}
    <p>You are not logged in.</p>
    <a href="{% url 'login'%}">Click here to login.</a>
{% endblock %}

DjangoProjekat/treninzi/templates/new.html
{% extends 'master.html' %}

{% block title %}
    New practice
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'demo_app:new' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.type.id_for_label }}">{{ form.type.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.type.id_for_label }}" name="{{ form.type.name }}">
            {% if form.type.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.type.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.location.id_for_label }}">{{ form.location.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.location.id_for_label }}" name="{{ form.location.name }}">
            {% if form.location.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.location.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.rate.id_for_label }}">{{ form.rate.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.rate.id_for_label }}" name="{{ form.rate.name }}">
            {% if form.rate.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.rate.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.hours.id_for_label }}">{{ form.hours.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.hours.id_for_label }}" name="{{ form.hours.name }}">
            {% if form.hours.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.hours.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.minutes.id_for_label }}">{{ form.minutes.label_tag }}</label>
            <input type="number" class="form-control" id="{{ form.minutes.id_for_label }}" name="{{ form.minutes.name }}">
            {% if form.minutes.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.minutes.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.content.id_for_label }}">{{ form.content.label_tag }}</label>
            <textarea class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.name }}" rows="5"></textarea>
            {% if form.content.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.content.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>

        <input type="submit" class="btn btn-primary btn-lg" value="Add"/>
    </form>

{% endblock %}

DjangoProjekat/treninzi/templates/practice.html
{% extends 'master.html' %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <h1>
                {{ practice.type }}
                {% if perms.demo_app.change_article %}
                    <a href="{% url 'demo_app:edit' practice.id %}">
                        <span class="badge badge-primary">Edit</span>
                    </a>
                {% endif %}
            </h1>
        </div>
        <div class ="card-body">
            <blockquote class="blockquote mb-0">
                <p>Lokacija: {{practice.location}}</p>
            </blockquote>
        </div>
        <div class ="card-body">
            <blockquote class="blockquote mb-0">
                <p>Ocena: {{practice.rate}}</p>
            </blockquote>
        </div>
        <div class ="card-body">
            <blockquote class="blockquote mb-0">
                <p>Trajanje: {{practice.hours}} hours, {{practice.minutes}} minutes</p>
            </blockquote>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>Komentar: </p>
                <p>{{ practice.content }}</p>
                <footer class="blockquote-footer">
                    Author:
                    <cite title="Source Title">
                        {{practice.owner}}
                    </cite>
                </footer>
            </blockquote>
        </div>
        <div class ="card-body">
            <blockquote class="blockquote mb-0">
                <p>Vreme: {{practice.created_at}}</p>
            </blockquote>
        </div>
    </div>

{% endblock %}

DjangoProjekat/treninzi/templates/practices.html
{%  extends 'master.html' %}

{% block title %}
    Django projekat
{% endblock %}

{%  block content %}
    <div class="list-group">
        {% for practice in practices %}
            <a class="list-group-item list-group-item-action" href="{% url 'demo_app:practice' practice.id %}">
                {{ practice.type }}
            </a>
        {% endfor %}
    </div>
{% endblock %}